spring.application.name=gcp-spanner
spring.cloud.gcp.spanner.instance-id=test-instance
spring.cloud.gcp.spanner.database=test-db
spring.cloud.gcp.project-id=single-planet-431805-t1
spring.cloud.gcp.credentials.location=file:/C:/Users/DELL/Desktop/Java Roadmap/Java Training/src/day10/gcp-spanner/gcpjson.json