spring.application.name=java-training-capstone
spring.cloud.gcp.spanner.instance-id=capstone-java-training
spring.cloud.gcp.spanner.database=capstone
spring.cloud.gcp.project-id=ultra-function-431620-h9
spring.cloud.gcp.credentials.location=file:/C:/Users/DELL/Desktop/Java Roadmap/Java Training/src/day16and17/java-training-capstone-order-service/ultra-function-431620-h9-6f1d736c91e7.json
logging.level.com.google.cloud.spring.data.spanner.core.SpannerTemplate=DEBUG
logging.level.com.google.cloud.spring.data.spanner.repository.support.SimpleSpannerRepository=DEBUG
logging.level.com.google.cloud.spanner=DEBUG
