version: "3.8"

services:
  pubsub:
    image: messagebird/gcloud-pubsub-emulator
    ports:
      - "8085:8681"
    environment:
      - PUBSUB_PROJECT_ID=test-project

  gcs:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    command:
      - -scheme
      - http
      - -public-host
      - localhost:4443
    volumes:
      - ./data:/data