spring.application.name=java-training-capstone-order-service
spring.cloud.gcp.spanner.instance-id=capstone-java-training
spring.cloud.gcp.spanner.database=capstone
spring.cloud.gcp.project-id=ultra-function-431620-h9
spring.cloud.gcp.credentials.location=file:/C:/Users/DELL/Desktop/Java Roadmap/Java Training/src/day16and17/java-training-capstone-order-service/ultra-function-431620-h9-6f1d736c91e7.json
logging.level.com.google.cloud.spring.data.spanner.core.SpannerTemplate=DEBUG
logging.level.com.google.cloud.spring.data.spanner.repository.support.SimpleSpannerRepository=DEBUG
logging.level.com.google.cloud.spanner=DEBUG

# Kafka Common Configuration
spring.kafka.bootstrap-servers=localhost:9092

# Producer Properties
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Logging Configuration
logging.level.com.example.java_training_capstone_order_service=INFO
logging.level.org.apache.kafka=WARN

server.port=8081
